# xPJP ukol 1
# kalina08@student.vspj.cz

CC = gcc
CFLAGS = -Wall -Werror

TARGET = ahoj
SRC = ahoj.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

