# xPJP ukol 2c
# kalina08@student.vspj.cz

CC = gcc
CFLAGS = -Wall -Werror

TARGET = c_automat_stub
SRC = c_automat_stub.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

